### ISSUE TITLE
Please use a unique package name 

### ISSUE THREAD

**Issue by jackyyf** [zxybazh/bookshop#1]
Using a package name like `workspace` is not a good idea, consider using `com.github.zxybazh.bookshop` :) 

~~Just for joking LOL :D~~

**Comment by zxybazh** [comment]
It's for convenience only QAQ. And would you please tell me why use `com.github.zxybazh.bookshop` maybe `zxybazh.bookshop` is enough LOL

**Comment by jackyyf** [comment]
Em... use `com.github.zxybazh.bookshop` is better according to [this documentation](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Also you can use your unique email address, like `com.gmail.zxybazh` if you have an email address `zxybazh@gmail.com`. Anyway, make sure to keep the package name unique, and everything else doesn't matter :D, so the later one is still acceptable.

**Comment by zxybazh** [comment]
OK, consider use that next time, thanks.
